"""AHE research report generator.
Reads research-findings.json + candidate-evaluations.json,
writes a human-readable markdown report to Obsidian vault.
Archives reports older than 30 days.
"""

import json
import shutil
from datetime import datetime, timedelta
from pathlib import Path

OBSIDIAN = Path.home() / "Documents" / "Obsidian Vault" / "Research" / "Autoresearch"
ARCHIVE = OBSIDIAN / "Archive"
KNOWLEDGE = Path.home() / ".autoresearch" / "knowledge"
SCRIPTS = Path.home() / "Scripts" / "logs"


def archive_old_reports(days=30):
    """Move ahe-research-*.md older than N days to Archive/."""
    if not OBSIDIAN.exists():
        return
    ARCHIVE.mkdir(parents=True, exist_ok=True)
    cutoff = datetime.now() - timedelta(days=days)
    for f in OBSIDIAN.glob("ahe-research-*.md"):
        try:
            mtime = datetime.fromtimestamp(f.stat().st_mtime)
            if mtime < cutoff:
                dest = ARCHIVE / f.name
                shutil.move(str(f), str(dest))
                print(f"  Archived: {f.name}")
        except Exception:
            pass


def format_candidate_detail(c, existing_map):
    """Generate a detailed markdown section for one candidate."""
    name = c["name"]
    cat = c.get("category", "other")
    score = c.get("score", 0)
    stars = c.get("stars", 0)
    url = c.get("url", "")
    desc = c.get("desc", "No description available")

    # What we have vs what we'd get
    have_text = {
        "database": "**None.** No database MCP server is installed. Database access requires manual SQL tools.",
        "monitoring": "**None.** No monitoring/Observability MCP is installed.",
        "web-scrape": "**brave-search** MCP. Provides search result URLs but not full page content extraction.",
        "terminal": "**None via MCP.** Shell commands run through pipeline scripts, not a dedicated MCP.",
        "code-graph": "**None.** No code indexing/graph MCP.",
        "other": "**Not directly covered** by current MCP inventory.",
    }
    add_text = {
        "database": f"Adds the ability to query databases ({', '.join(c.get('dbs', ['PostgreSQL', 'MySQL', 'SQLite']))}) via natural language. The agent can list tables, execute queries, and explore schema without manual SQL connections.",
        "monitoring": "Adds system observability. The agent can check application logs, monitor performance metrics, and alert on anomalies.",
        "web-scrape": "Adds full web page content extraction. Beyond search results: can read, parse, and extract structured data from any URL.",
        "terminal": "Adds isolated terminal/command execution as a proper MCP tool. Commands run with defined permissions and timeouts.",
        "code-graph": "Adds codebase indexing. The agent can query code structure, find dependencies, trace function calls across files.",
        "other": desc,
    }
    why_surfaced = (
        f"Score: **{score}/100** — {stars:,} GitHub stars. "
        f"Found via GitHub search for '{cat}' category MCP servers. "
        f"Filtered against 7 existing MCPs to avoid duplicates."
    )

    section = f"""
### {name}
**Category:** {cat} | **Score:** {score}/100 | **Stars:** {stars:,}
**URL:** {url}

**What we have today:** {have_text.get(cat, have_text['other'])}

**What this adds:** {add_text.get(cat, add_text['other'])}

**Why surfaced:** {why_surfaced}

"""
    return section


def generate_report():
    """Generate the full markdown report and write to Obsidian."""
    OBSIDIAN.mkdir(parents=True, exist_ok=True)

    # Load data
    findings_file = KNOWLEDGE / "research-findings.json"
    evals_file = KNOWLEDGE / "candidate-evaluations.json"

    if not findings_file.exists():
        print(json.dumps({"error": "No findings. Run ahe-research-module.py first."}))
        return

    findings = json.loads(findings_file.read_text())
    evals = json.loads(evals_file.read_text()) if evals_file.exists() else {"scored": []}

    candidates = evals.get("scored", [])
    gaps = findings.get("gaps", [])
    ts = findings.get("ts", datetime.now().isoformat())

    today = datetime.now().strftime("%Y-%m-%d")
    report_name = f"ahe-research-{today}.md"
    report_path = OBSIDIAN / report_name

    # Build existing capability map
    existing = {
        "filesystem": "File read/write MCP",
        "github": "GitHub API MCP",
        "brave-search": "Web search MCP",
        "context7": "Documentation query MCP",
        "chrome-devtools": "Browser automation MCP",
        "qwen-memory": "Persistent memory MCP",
        "autocontext": "Agent evaluation MCP",
    }

    # Build report
    lines = []
    lines.append(f"# AHE Research Report — {today}")
    lines.append("")
    lines.append("> Auto-generated by the AHE self-improvement pipeline.")
    lines.append("> This report summarizes discovered candidates, config gaps, and recommended actions.")
    lines.append("")

    # Summary section
    lines.append("## Summary")
    lines.append("")
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| New MCP candidates | {len(candidates)} |")
    lines.append(f"| Config gaps found | {len(gaps)} |")
    lines.append(f"| Top candidate score | {candidates[0]['score'] if candidates else 0}/100 |")
    top_name = candidates[0]['name'] if candidates else "None"
    lines.append(f"| Top recommendation | {top_name} |")
    lines.append("")

    # Leaderboard table
    lines.append("## Candidate Leaderboard")
    lines.append("")
    lines.append("| Rank | Score | Candidate | Category | What it adds |")
    lines.append("|------|-------|-----------|----------|-------------|")
    for i, c in enumerate(candidates[:15], 1):
        add_brief = {
            "database": "Database query via natural language",
            "monitoring": "System observability",
            "web-scrape": "Full page content extraction",
            "terminal": "Isolated terminal MCP",
            "code-graph": "Code indexing & graph queries",
            "other": c.get("desc", "")[:60],
        }.get(c.get("category", "other"), "")
        lines.append(f"| {i} | **{c['score']}** | {c['name']} | {c.get('category','other')} | {add_brief} |")
    lines.append("")

    # Detailed sections
    lines.append("## Detailed Recommendations")
    lines.append("")
    for c in candidates[:10]:
        lines.append(format_candidate_detail(c, existing))
        lines.append("---")

    # Config gaps
    if gaps:
        lines.append("## Config Gaps")
        lines.append("")
        lines.append("The following benchmark tests are currently failing:")
        lines.append("")
        lines.append("| Test | Detail | Suggested Fix |")
        lines.append("|------|--------|---------------|")
        for g in gaps:
            fix = {
                "mcp.brave_key": "Set BRAVE_API_KEY user env var",
                "hard.security_hook_keys": "Add GEMINI_API_KEY to exclusion list in bm-module.ps1",
                "scenario.stability": "Natural improvement with consistent benchmark runs",
            }.get(g.get("test", ""), "Investigate")
            lines.append(f"| {g.get('test','')} | {g.get('detail','')} | {fix} |")
        lines.append("")

    # Current MCP inventory
    lines.append("## Current MCP Inventory")
    lines.append("")
    lines.append("| MCP | What it provides |")
    lines.append("|-----|-----------------|")
    for name, what in sorted(existing.items()):
        lines.append(f"| {name} | {what} |")
    lines.append("")

    # Methodology
    lines.append("## Methodology")
    lines.append("")
    lines.append("Candidates are discovered through:")
    lines.append("- **GitHub API search** by capability category (database, monitoring, search, etc.)")
    lines.append("- **Star count** as a quality signal (minimum 200 stars)")
    lines.append("- **Dedup** against 7 existing MCPs to avoid recommending what's already installed")
    lines.append("- **Gap analysis** from latest benchmark results")
    lines.append("")
    lines.append("Scores are computed as:")
    lines.append("- **Star points** (0-20): `stars / 500`, capped at 20")
    lines.append("- **Gap fill** (0-50): How badly we need this capability, weighted by benchmark impact")
    lines.append("- **Relevance** (0-15): Whether the candidate's description matches its category")
    lines.append("- **Safety** (0-10): npm-based vs binary install")
    lines.append("")

    # Footer
    lines.append("---")
    lines.append(f"*Generated at {datetime.now().strftime('%Y-%m-%d %H:%M')} by AHE pipeline*")
    lines.append(f"*Raw data: `{KNOWLEDGE / 'research-findings.json'}`*")

    report_text = "\n".join(lines)

    # Archive old, write new
    archive_old_reports(30)
    report_path.write_text(report_text, encoding="utf-8")

    print(json.dumps({"status": "ok", "report": str(report_path), "candidates": len(candidates)}))


if __name__ == "__main__":
    generate_report()
